[package]
name = "json-ld-testing-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macro for JSON-LD test suite generation"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
json-ld = { path = "../.." }
json-ld-testing-core = { path = "../core", features = ["proc_macro2"] }
